#!/usr/bin/env zsh

setnullopt=0

# Zsh errors when globs don't match anything.
if [ ! -o NULL_GLOB ]; then
	setopt NULL_GLOB
	setnullopt=1
fi

echo "Formatting all .h, .hpp, and .cpp in all subdirectories..."
clang-format -i -style=file -- **/*.{[ch]pp,h}

if [ $setnullopt -ne 0 ]; then
	unsetopt NULL_GLOB
fi
