#!/usr/bin/env bash

set -e

rebuild=0
cppstandard="c++23"
buildargs="-std=$cppstandard -Wall -Werror"
cppfiles="game.cpp find_sets.cpp cards.cpp output.cpp"

usage() {
    echo "Optionally builds, and then runs the set solver program."
    echo "  Usage: Pass -r to rebuild."
}

while test $# != 0; do
    case "$1" in
    -r) rebuild=1 ;;
    *)
        usage
        exit 0
        ;;
    esac
    shift
done

if [ $rebuild -ne 0 ]; then
    echo "Build time:"
    time g++ $buildargs $cppfiles -o build/find_sets
fi

# Thanks Stack Overflow: https://stackoverflow.com/questions/11027679/capture-stdout-and-stderr-into-different-variables
{
    IFS=$'\n' read -r -d '' RUNTIME
    IFS=$'\n' read -r -d '' OUTPUT
} < <((printf '\0%s\0' "$(time ./build/find_sets)" 1>&2) 2>&1)

printf -- "\n---\n\n"
printf '%s\n\n' "$OUTPUT"
printf -- "---\n\n"
printf "Run time:\n\n"
printf '%s\n' "$RUNTIME"
